#import "global.typ": *

= Grundlagen


== Graphentheorie

Straßennetzwerke werden in der Informatik als mathematische Graphen modelliert. Ein Graph G ist definiert als G = (V, E), wobei V die Menge der Knoten und E die Menge der Kanten bezeichnet [Zitat: Lehrbuch Graphentheorie — TODO: geeignete Quelle suchen, z.B. Cormen et al. 2009]. Knoten repräsentieren dabei Kreuzungen und Kanten die Straßenabschnitte zwischen ihnen. Kanten können zusätzlich mit einer Gewichtsfunktion w: E → ℝ⁺ versehen werden, die beispielsweise die Länge eines Straßenabschnitts oder die benötigte Fahrzeit kodiert. Darüber hinaus können Kanten eine Richtung besitzen, wodurch sich Einbahnstraßen natürlich abbilden lassen.
Der in dieser Arbeit verwendete Straßengraph ist sowohl gerichtet als auch gewichtet. Die Kantengewichte repräsentieren die Distanz in Metern, die Richtung der Kanten kodiert die Befahrbarkeit der jeweiligen Straßenabschnitte.
Ein Pfad P von Knoten u nach Knoten v ist eine Folge von Knoten (v₁, v₂, ..., vₙ) mit v₁ = u und vₙ = v, wobei zwischen je zwei aufeinanderfolgenden Knoten eine gerichtete Kante existiert. Der kürzeste Pfad ist derjenige Pfad, für den die Summe der Kantengewichte minimal ist.
Zur Speicherung des Graphen wird eine Adjazenzliste verwendet. Eine Adjazenzmatrix würde für einen Graphen mit N Knoten einen Speicherbedarf von O(N²) erfordern, was bei der Knotenzahl eines städtischen Straßennetzwerks nicht praktikabel wäre. Straßengraphen sind dünn besetzt, da jeder Knoten im Durchschnitt nur wenige Nachbarn besitzt. Eine Kreuzung hat typischerweise drei bis vier eingehende oder ausgehende Verbindungen. Die Adjazenzliste benötigt daher nur O(N + E) Speicher und ist damit die geeignete Datenstruktur für diesen Anwendungsfall.

==  Kürzeste-Wege-Algorithmen

=== Dijkstra

Der Dijkstra-Algorithmus [Zitat: Dijkstra 1959] berechnet den kürzesten Weg von einem Startknoten zu allen anderen Knoten eines gewichteten Graphen. Der Algorithmus verwaltet eine Priority Queue, die stets den Knoten mit der aktuell geringsten bekannten Distanz zum Startknoten als nächstes zur Verarbeitung bereitstellt. Auf diese Weise wird sichergestellt, dass jeder Knoten beim ersten Besuch bereits mit dem kürzesten Weg erreicht wurde. Eine notwendige Voraussetzung für die Korrektheit des Algorithmus ist, dass alle Kantengewichte nicht-negativ sind [Zitat: Dijkstra 1959].
Wird nicht der kürzeste Weg zu allen Knoten, sondern nur zu einem bestimmten Zielknoten gesucht, kann der Algorithmus abgebrochen werden sobald der Zielknoten aus der Priority Queue entnommen wird. Zu diesem Zeitpunkt ist garantiert, dass der kürzeste Weg zum Zielknoten gefunden wurde.
In der vorliegenden Implementierung wird Dijkstra in zwei unterschiedlichen Rollen eingesetzt: Im Preprocessing dient er der Berechnung optimaler Kantengewichte zwischen Gate-Node-Paaren innerhalb eines Clusters. Im Benchmarking wird er als Referenzalgorithmus ohne hierarchische Erweiterung verwendet.

=== A\*

Der A\*-Algorithmus [Zitat: Hart et al. 1968] erweitert Dijkstra um eine Heuristikfunktion h(n), die die geschätzten Kosten vom aktuellen Knoten n zum Zielknoten abschätzt. Die Bewertungsfunktion lautet:
f(n) = g(n) + h(n)
wobei g(n) die tatsächlichen Kosten vom Startknoten bis zum Knoten n bezeichnet und h(n) die heuristische Schätzung der verbleibenden Kosten bis zum Ziel. Die Priority Queue priorisiert Knoten nach ihrem f(n)-Wert, wodurch die Suche zielgerichtet erfolgt und im Vergleich zu Dijkstra deutlich weniger Knoten expandiert werden müssen [Zitat: Hart et al. 1968].
Eine Heuristik gilt als admissibel, wenn sie die tatsächlichen Kosten zum Ziel niemals überschätzt. Nur unter dieser Bedingung garantiert A\* die Optimalität des gefundenen Pfades. In der vorliegenden Implementierung wird die Haversine-Formel als Heuristik verwendet, die den Großkreisabstand zwischen zwei geografischen Koordinaten berechnet. Da die Luftliniendistanz zwischen zwei Punkten stets kleiner oder gleich der tatsächlichen Wegstrecke im Straßennetz ist, erfüllt die Haversine-Formel die Admissibilitätsbedingung.

=== Breitensuche (BFS)

Die Breitensuche (BFS, englisch: Breadth-First Search) ist ein grundlegender Graphtraversierungsalgorithmus [Zitat: Cormen et al. 2009]. Ausgehend von einem Startknoten durchläuft BFS den Graphen schichtweise: zunächst werden alle direkten Nachbarn des Startknotens besucht, anschließend deren Nachbarn, und so weiter. Die Reihenfolge der Verarbeitung wird durch eine FIFO-Queue gesteuert, die sicherstellt dass Knoten in der Reihenfolge ihres Entdeckens verarbeitet werden.
Im Gegensatz zu Dijkstra und A\* berücksichtigt BFS keine Kantengewichte. Dies macht BFS ungeeignet für die Berechnung kürzester Wege in gewichteten Graphen, jedoch ideal für Anwendungsfälle bei denen eine gleichmäßige Ausbreitung im Graphen ohne Gewichtung gewünscht ist.
In der vorliegenden Implementierung wird BFS zur Schätzung der strukturellen Dimension des Straßennetzes verwendet, basierend auf der Evaluationsmethodik von Sturtevant (2012) [Zitat: Sturtevant 2012]. Dabei wird gemessen wie schnell sich die Anzahl erreichbarer Knoten mit zunehmender Suchtiefe ausbreitet. Wächst die Anzahl erreichbarer Knoten linear mit der Entfernung, verhält sich das Netz wie eine eindimensionale Struktur, etwa eine Schnellstraße ohne Abzweigungen. Wächst sie quadratisch, verhält sich das Netz wie ein zweidimensionales Gitter, was typisch für ein städtisches Straßennetz mit vielen Kreuzungen ist. Diese Dimensionsmetrik gibt Aufschluss über die strukturelle Komplexität des untersuchten Straßennetzes und dient als ergänzende Kontextinformation für die Bewertung der Benchmarking-Ergebnisse.

=== Alternative Verfahren

Über A\* hinaus existiert eine Reihe weiterer Algorithmen zur kürzesten-Wege-Berechnung, die für sehr große Straßennetze entwickelt wurden. Die folgende Übersicht beschränkt sich auf die für diese Arbeit relevanten Ansätze und ordnet sie im Verhältnis zu A\* ein.

Die bidirektionale Suche @Pohl:1971 startet zwei Suchläufe gleichzeitig, einen vom Startknoten in Vorwärtsrichtung und einen vom Zielknoten in Rückwärtsrichtung. Die Suche endet, sobald sich die beiden Suchfronten in einem gemeinsamen Knoten treffen. Da die in der Suchfront betrachteten Knoten näherungsweise mit dem Quadrat des Suchradius wachsen, halbiert sich der zu erkundende Suchradius pro Richtung, was die Gesamtzahl expandierter Knoten in der Praxis deutlich reduziert. Der Ansatz lässt sich sowohl auf Dijkstra als auch auf A\* anwenden, erfordert im heuristischen Fall jedoch Sorgfalt bei der Definition der Heuristik in beiden Richtungen, um die Optimalität zu erhalten. Bidirektionale Suche benötigt keine Vorberechnung und ist daher unmittelbar einsetzbar, bringt aber gegenüber A\* nur einen konstanten Faktor an Beschleunigung.

ALT (A\*, Landmarks, Triangle inequality) @Goldberg:2005 erweitert A\* um eine Landmark-basierte Heuristik. In einer einmaligen Vorberechnung werden für eine kleine Auswahl von Landmark-Knoten die exakten Distanzen zu allen anderen Knoten gespeichert. Zur Anfragezeit liefert die Dreiecksungleichung über diese vorberechneten Distanzen eine zulässige untere Schranke für die verbleibenden Kosten zum Ziel, die in der Regel deutlich enger ist als die euklidische Heuristik. Dadurch werden weniger irrelevante Knoten expandiert. ALT ist konzeptionell nah an A\* und behält dessen Optimalitätsgarantien, setzt jedoch im Gegensatz zu A\* eine Vorverarbeitung des Graphen voraus.

Contraction Hierarchies (CH) @Geisberger:2008 verfolgen einen weitergehenden Ansatz. In der Vorberechnung werden alle Knoten nach einem Wichtigkeitskriterium sortiert und nacheinander aus dem Graphen kontrahiert. Beim Kontrahieren eines Knotens werden Shortcut-Kanten zwischen seinen Nachbarn eingefügt, sofern diese den kürzesten Pfad über den entfernten Knoten ersetzen. Zur Anfragezeit kommt eine bidirektionale Dijkstra-Variante zum Einsatz, die ausschließlich Kanten zu höher eingestuften Knoten verfolgt. Die Suche durchläuft dadurch nur einen Bruchteil des ursprünglichen Graphen. CH liefert auf Straßennetzen kontinentaler Größe Antwortzeiten im Sub-Millisekunden-Bereich und bildet die Grundlage zahlreicher produktiver Routingsysteme.

Diese drei Verfahren markieren unterschiedliche Punkte im Spektrum zwischen Anfragezeit und Vorberechnungsaufwand. A\* selbst benötigt keinerlei Vorverarbeitung und ist dadurch der robuste Default für Anwendungsfälle, in denen der Graph häufig wechselt oder klein genug bleibt, um online effizient durchsucht werden zu können. Dies betrifft etwa Spielebenen, Roboterplanung oder kleinere Kartenausschnitte. Sobald der Graph statisch ist und sehr viele Anfragen darauf beantwortet werden müssen, dominieren preprocessing-basierte Verfahren wie CH; reines A\* ist dort nicht mehr wettbewerbsfähig. Das in dieser Arbeit untersuchte HPA\* lässt sich in dieses Spektrum als ein Verfahren einordnen, das einen einfachen, gut verständlichen Vorberechnungsschritt mit einem nahezu unveränderten A\* zur Anfragezeit kombiniert. Es bleibt damit konzeptionell näher an A\* als CH, profitiert aber bereits von der hierarchischen Struktur.

==  Hierarchisches Routing

Das Grundprinzip hierarchischen Routings besteht darin, vom ursprünglichen Graphen eine abstrahierte Version zu erzeugen, auf der zunächst eine grobe Wegplanung durchgeführt wird, die anschließend schrittweise verfeinert wird [Zitat: Botea et al. 2004]. Dieser Ansatz reduziert den Suchraum erheblich, da der Großteil der Suche auf dem deutlich kleineren abstrakten Graphen stattfindet.
Die Erstellung der Hierarchie erfolgt in einer einmaligen Build-Phase. Der Graph wird zunächst in disjunkte Cluster partitioniert. Anschließend werden die Grenzknoten zwischen benachbarten Clustern als Gate Nodes definiert. Jedes Gate wird zu einem Knoten im abstrakten Graphen. Gate Nodes desselben Clusters werden durch vorberechnete Kanten verbunden, deren Gewichte den optimalen Pfadkosten zwischen diesen Gates innerhalb des Clusters entsprechen. In der vorliegenden Implementierung werden diese Kantengewichte mittels lokalem A\*, beschränkt auf die Grenzen des jeweiligen Clusters, berechnet. Diese Entscheidung stellt sicher, dass der abstrakte Graph die tatsächlichen Kosten eines A\*-Laufs abbildet, was die Vergleichbarkeit beider Algorithmen gewährleistet.
Die Vorberechnung aller Kantengewichte im abstrakten Graphen hat eine Komplexität von O(k² · A\*) pro Cluster, wobei k die Anzahl der Gate Nodes pro Cluster bezeichnet. In dicht besiedelten Regionen kann ein Cluster eine erhebliche Anzahl an Gate Nodes aufweisen, was die Vorberechnungskosten entsprechend erhöht. Produktionssysteme begegnen diesem Problem durch gezielte Gate-Selektion, die nur die relevantesten Übergänge zwischen Clustern berücksichtigt [Zitat: OsmAnd 2025].
Zur Anfragezeit wird zunächst mit A\* vom Startpunkt zum nächsten Gate des eigenen Clusters navigiert. Anschließend wird A\* auf dem abstrakten Graphen ausgeführt, wobei die durchlaufenen Cluster gespeichert werden. Nach Erreichen des Zielclusters wird erneut auf die untere Abstraktionsebene gewechselt und mit A\* zum Zielknoten navigiert. Abschließend wird für jeden durchlaufenen Cluster A\* vom Entry Gate zum Exit Gate ausgeführt, um den vollständigen Pfad zu rekonstruieren [Zitat: Botea et al. 2004].

Konzeptionell folgt hierarchisches Routing dem Prinzip des _Level of Detail_ (LOD), das in der Computergrafik etabliert ist: Entfernte oder für die aktuelle Betrachtung irrelevante Bereiche werden in einer gröberen Auflösung dargestellt, während nahegelegene Bereiche in voller Detailtiefe verbleiben. Übertragen auf die Pfadsuche bedeutet dies, dass Cluster, die zwischen Start- und Zielregion liegen, nur auf der abstrakten Ebene durchlaufen werden, während die Start- und Zielregion auf dem vollständigen Basisgraphen bearbeitet werden. Mehrere Hierarchieebenen würden dieses Prinzip weiter fortsetzen, indem für zunehmend entfernte Regionen immer gröbere Abstraktionen verwendet werden. Die vorliegende Arbeit beschränkt sich auf eine einzelne Hierarchieebene.

== Network Voronoi <voronoi-clustering>

== OpenStreetMap als Datenbasis

OpenStreetMap (OSM) ist ein offenes, gemeinschaftlich gepflegtes Kartenprojekt, das geografische Daten unter der Open Database License (ODbL) frei zur Verfügung stellt [Zitat: OpenStreetMap Foundation — TODO: OSM-Referenz suchen, z.B. Haklay & Weber 2008]. Im Gegensatz zu kommerziellen Kartendiensten sind die Daten kostenlos zugänglich, reproduzierbar und für andere Forschende einsehbar, was OSM besonders für wissenschaftliche Arbeiten geeignet macht.
Das OSM-Datenmodell basiert auf drei Grundelementen. Nodes sind einzelne Punkte mit geografischen Koordinaten in Form von Längen- und Breitengraden und repräsentieren beispielsweise Kreuzungen oder Points of Interest. Ways sind geordnete Listen von Nodes und repräsentieren Straßen, Wege oder Flächen. Relations gruppieren mehrere Nodes, Ways oder andere Relations zu einer definierten Beziehung, etwa einer Fahrradroute. Alle drei Elemente können mit Tags versehen werden, die aus Schlüssel-Wert-Paaren bestehen, beispielsweise highway=cycleway oder oneway=yes, und semantische Informationen über das jeweilige Element kodieren.
Zur Abfrage und Verarbeitung der OSM-Daten wird in dieser Arbeit die Python-Bibliothek osmnx verwendet [Zitat: Boeing 2017 — TODO: osmnx Paper suchen]. Über die Funktion graph_from_point() wird ein Graph anhand eines Mittelpunkts, eines Radius und eines Netzwerktyps abgefragt. Als Netzwerktyp wird network_type="bike" verwendet, wodurch ausschließlich das für Fahrräder befahrbare Straßennetz geladen wird. Das Ergebnis ist ein networkx MultiDiGraph, also ein gerichteter Graph der mehrere parallele Kanten zwischen denselben Knoten erlaubt. Dies ist notwendig, da Straßenabschnitte in unterschiedlichen Richtungen verschiedene Eigenschaften besitzen können.
Standardmäßig vereinfacht osmnx den Graphen mit simplify=True: Knoten die lediglich geometrische Wegpunkte auf geraden Straßen darstellen und keine echten Kreuzungen repräsentieren, werden entfernt und die zugehörigen Kanten direkt verbunden. Dies reduziert die Graphgröße erheblich ohne die topologische Struktur des Netzwerks zu verändern. Der resultierende Graph wird im GraphML-Format lokal gespeichert, um wiederholte Abfragen der OSM-Server zu vermeiden.

== Koordinatensysteme <koordinatensysteme>

Geografische Daten können in unterschiedlichen Koordinatensystemen repräsentiert werden, die je nach Anwendungsfall unterschiedliche Vor- und Nachteile aufweisen.
OSM-Daten werden standardmäßig im WGS84-Referenzsystem gespeichert @OSMWGS84:2026. WGS84 ist ein sphärisches Koordinatensystem das Positionen auf der Erdoberfläche durch Längen- und Breitengrade beschreibt. Es ist der weltweite Standard für GPS- und Navigationssysteme. Da WGS84 auf einem Ellipsoid basiert, sind direkte euklidische Distanzberechnungen zwischen zwei Koordinatenpaaren nicht möglich. Ein Grad Längengrad entspricht in Berlin einer anderen Distanz als am Äquator.
Das UTM-Koordinatensystem (Universal Transverse Mercator) projiziert die Erdoberfläche auf eine zweidimensionale kartesische Ebene mit Metern als Einheit. Innerhalb einer UTM-Zone sind euklidische Distanzberechnungen möglich und liefern für kleine bis mittlere Gebiete wie Berlin hinreichend genaue Ergebnisse.
In der vorliegenden Implementierung wird der Graph mittels ox.project_graph() einmalig in das UTM-Koordinatensystem projiziert, um das Seed-Grid für die Clusterpartitionierung zu berechnen. Das Seed-Grid arbeitet mit kartesischen Koordinaten in Metern, was eine gleichmäßige räumliche Verteilung der Seedpunkte über die Karte ermöglicht. Nach der Seed-Berechnung werden alle weiteren Operationen auf dem ursprünglichen WGS84-Graphen ausgeführt.