#import "global.typ": *

= Verwandte Arbeiten

Dieses Kapitel ordnet die vorliegende Arbeit in den Kontext bestehender Forschung ein. Die Darstellung gliedert sich entlang dreier Achsen: hierarchische Pfadsuche in Spielwelten, aus der HPA\* ursprünglich stammt (@sec:rw-games), hierarchisches Routing in Straßennetzen (@sec:rw-roads) sowie Evaluationsmethodik für Pfadsuchalgorithmen (@sec:rw-eval). Für jede Achse werden die zentralen Arbeiten vorgestellt und die Abgrenzung zur vorliegenden Untersuchung herausgearbeitet.

== Hierarchische Pfadsuche in Spielwelten <sec:rw-games>

Die Originalarbeit von Botea, Müller und Schaeffer @Botea:2004 führt HPA\* als hierarchisches Pfadsuchverfahren für gitterbasierte Spielkarten ein. Der Algorithmus partitioniert die Karte in rechteckige Cluster fester Größe, identifiziert Übergangspunkte (Entrances) an den Clustergrenzen und verbindet diese durch vorberechnete Intra-Cluster-Kanten zu einem abstrakten Graphen. Zur Anfragezeit wird zunächst auf dem abstrakten Graphen gesucht und das Ergebnis anschließend auf den Basisgraphen verfeinert. Botea et al. berichten eine Reduktion der expandierten Knoten um den Faktor 10 bei einer Pfadsuboptimalität von unter 1% nach einer nachgelagerten Glättung.

Die vorliegende Arbeit übernimmt das Grundprinzip von HPA\*, also Partitionierung, Abstraktion, Suche auf dem abstrakten Graphen und Verfeinerung, weicht jedoch in mehreren Punkten vom Original ab. Erstens operiert sie auf realen Straßengraphen statt auf regulären Gittern, was eine andere Clustering-Strategie erfordert. Das reguläre Gitter-Clustering von Botea et al. setzt eine gleichmäßige Topologie voraus, die in Straßennetzen nicht gegeben ist. Zweitens verwendet die vorliegende Arbeit Network Voronoi Diagrams @Kolahdouzan:2004 zur Partitionierung, die die Netzwerkstruktur respektieren und zusammenhängende Cluster garantieren. Drittens verzichtet die vorliegende Implementierung auf Pfadglättung und evaluiert stattdessen die Pfadqualität ohne nachgelagerte Optimierung.

Sturtevant und Buro @Sturtevant:2005 erweitern HPA\* um partielle Verfeinerung (PRA\*). Dabei wird nicht der gesamte abstrakte Pfad auf einmal verfeinert, sondern nur der unmittelbar benötigte Abschnitt. Dies reduziert den Rechenaufwand in Szenarien, in denen sich das Ziel während der Bewegung ändern kann, etwa bei KI-gesteuerten Spielcharakteren. Da die vorliegende Arbeit statische Anfragen auf einem unveränderlichen Graphen untersucht, ist partielle Verfeinerung hier nicht relevant. Alle Anfragen werden vollständig verfeinert.

Harabor und Grastien @Harabor:2011 verfolgen mit Jump Point Search (JPS) einen orthogonalen Ansatz zur Beschleunigung von A\* auf Gitter-Karten. JPS eliminiert symmetrische Pfade durch geometrische Sprungregeln und reduziert dadurch die Anzahl expandierter Knoten drastisch, ohne Vorverarbeitung und ohne Optimalitätsverlust. Der Ansatz ist jedoch auf uniforme Gitter beschränkt und nicht auf gewichtete Straßengraphen übertragbar. Er verdeutlicht, dass die Eigenschaften der Graphstruktur für die Wahl des Beschleunigungsverfahrens entscheidend sind.

== Hierarchisches Routing in Straßennetzen <sec:rw-roads>

Für Straßennetze sind in den letzten zwei Jahrzehnten leistungsfähige Vorverarbeitungsverfahren entwickelt worden, die A\* in produktiven Anwendungen weitgehend abgelöst haben. Delling et al. @Delling:2009 bieten eine umfassende Übersicht über diese Verfahren und ordnen sie in ein Spektrum zwischen Vorberechnungsaufwand und Anfragezeit ein.

Contraction Hierarchies (CH) @Geisberger:2008 kontrahieren Knoten in aufsteigender Wichtigkeitsreihenfolge und fügen Shortcut-Kanten ein, die kürzeste Pfade über kontrahierte Knoten ersetzen. Zur Anfragezeit genügt eine bidirektionale Dijkstra-Suche, die ausschließlich zu wichtigeren Knoten aufsteigt. CH erzielen auf kontinentalen Straßennetzen Antwortzeiten im Sub-Millisekunden-Bereich und bilden die Grundlage zahlreicher produktiver Systeme, darunter OSRM @Luxen:2011. Im Vergleich zu HPA\* sind CH konzeptionell aufwändiger: Die Knotenordnung erfordert eine globale Analyse des gesamten Graphen, während HPA\* lediglich eine lokale Partitionierung vornimmt. Zudem garantieren CH optimale Pfade, während HPA\* ohne Glättung suboptimale Pfade liefern kann.

Transit Node Routing @Bast:2007 identifiziert eine kleine Menge von Transitknoten, durch die nahezu alle langen Pfade verlaufen. Für jedes Knotenpaar werden die relevanten Transitknoten und deren Distanzen vorberechnet. Anfragen zwischen weit entfernten Knoten lassen sich dadurch durch wenige Tabellenzugriffe beantworten, ganz ohne Graphsuche. Das Verfahren erzielt die schnellsten bekannten Anfragezeiten für Straßennetze, erfordert jedoch erheblichen Speicher- und Vorberechnungsaufwand. Die konzeptionelle Verwandtschaft zu HPA\* liegt in der Beobachtung, dass lange Pfade durch eine überschaubare Menge von Übergangspunkten verlaufen. HPA\* formalisiert diese Beobachtung über Cluster-Grenzen, Transit Node Routing über eine globale Zugangsknoten-Berechnung.

ALT (A\*, Landmarks, Triangle inequality) @Goldberg:2005 stärkt die Heuristik von A\* durch vorberechnete Landmark-Distanzen, ohne die Graphstruktur selbst zu verändern. Der Ansatz ist konzeptionell einfacher als CH oder HPA\*, da er weder Kontraktionen noch Cluster-Partitionierungen einführt, bietet dafür aber geringere Beschleunigungsfaktoren.

Unter den produktiven Routing-Systemen ist OsmAnd @OsmAnd:2024 für die vorliegende Arbeit besonders relevant, da es ebenfalls eine hierarchische Partitionierung auf OpenStreetMap-Daten anwendet. OsmAnd verwendet eine HPA\*-ähnliche Architektur mit mehreren Hierarchieebenen und einer optimierten Gate-Selektion, die nur die verkehrlich relevantesten Übergangspunkte zwischen Regionen berücksichtigt. Die vorliegende Arbeit untersucht demgegenüber eine vereinfachte Variante mit einer einzelnen Hierarchieebene und ohne Gate-Filterung, um den isolierten Effekt der hierarchischen Abstraktion zu messen.

== Evaluationsmethodik <sec:rw-eval>

Die Evaluation von Pfadsuchalgorithmen erfordert eine Stichprobenmethodik, die unterschiedliche Pfadlängen systematisch abdeckt. Eine rein zufällige Auswahl von Start- und Zielpaaren würde die natürliche Verteilung der Pfadlängen in der zugrundeliegenden Karte widerspiegeln und könnte bestimmte Distanzbereiche über- oder unterrepräsentieren.

Sturtevant @Sturtevant:2012 schlägt für gitterbasierte Pfadsuche eine Stratifizierung nach der optimalen Pfadlänge vor. Start- und Zielpaare werden in Buckets gleicher Breite gruppiert, wobei jedes Bucket eine feste Anzahl von Problemen enthält. Dies gewährleistet, dass die Evaluation alle relevanten Distanzbereiche gleichmäßig abdeckt, und ermöglicht die Analyse des Algorithmenverhaltens als Funktion der Pfadlänge.

Die vorliegende Arbeit adaptiert Sturtevants Methodik für reale Straßengraphen. Die Buckets werden nach der A\*-Referenzdistanz in Metern gebildet (500 m Breite, 10 Probleme pro Bucket), und die Stichprobe wird auf die größte zusammenhängende Komponente des Graphen beschränkt. Diese Adaption ist notwendig, da Straßengraphen im Gegensatz zu Gittern keine garantierte Konnektivität zwischen beliebigen Knotenpaaren aufweisen und die natürliche Distanzmetrik Meter statt Gitterschritte ist. Die Auswertung nach Distanzbuckets erlaubt insbesondere die Identifikation eines Break-Even-Punkts, ab dem HPA\* gegenüber A\* einen Laufzeitvorteil erzielt. Diese Fragestellung bliebe bei reinen Durchschnittswerten verborgen.
